/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ForecastRecord = IDL.Record({
  'predictedLoad' : IDL.Float64,
  'isPeak' : IDL.Bool,
  'actualLoad' : IDL.Float64,
  'timestamp' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'acknowledged' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Text,
  'severity' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DatasetMetadata = IDL.Record({
  'missingValues' : IDL.Nat,
  'filename' : IDL.Text,
  'timeRange' : IDL.Text,
  'rowCount' : IDL.Nat,
  'uploadedAt' : IDL.Text,
});
export const ModelSettings = IDL.Record({
  'refreshRate' : IDL.Nat,
  'learningRate' : IDL.Text,
  'xgboostMaxDepth' : IDL.Nat,
  'lstmEpochs' : IDL.Nat,
  'batchSize' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acknowledgeAlert' : IDL.Func([IDL.Nat], [], []),
  'addAlert' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addForecastRecord' : IDL.Func([ForecastRecord], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearForecastRecords' : IDL.Func([], [], []),
  'getAllAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAllForecastRecords' : IDL.Func([], [IDL.Vec(ForecastRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDatasetMetadata' : IDL.Func([], [IDL.Opt(DatasetMetadata)], ['query']),
  'getModelSettings' : IDL.Func([], [ModelSettings], ['query']),
  'getSimulationMode' : IDL.Func([], [IDL.Bool], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDatasetMetadata' : IDL.Func([DatasetMetadata], [], []),
  'setSimulationMode' : IDL.Func([IDL.Bool], [], []),
  'updateModelSettings' : IDL.Func([ModelSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ForecastRecord = IDL.Record({
    'predictedLoad' : IDL.Float64,
    'isPeak' : IDL.Bool,
    'actualLoad' : IDL.Float64,
    'timestamp' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'acknowledged' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Text,
    'severity' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DatasetMetadata = IDL.Record({
    'missingValues' : IDL.Nat,
    'filename' : IDL.Text,
    'timeRange' : IDL.Text,
    'rowCount' : IDL.Nat,
    'uploadedAt' : IDL.Text,
  });
  const ModelSettings = IDL.Record({
    'refreshRate' : IDL.Nat,
    'learningRate' : IDL.Text,
    'xgboostMaxDepth' : IDL.Nat,
    'lstmEpochs' : IDL.Nat,
    'batchSize' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acknowledgeAlert' : IDL.Func([IDL.Nat], [], []),
    'addAlert' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addForecastRecord' : IDL.Func([ForecastRecord], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearForecastRecords' : IDL.Func([], [], []),
    'getAllAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAllForecastRecords' : IDL.Func(
        [],
        [IDL.Vec(ForecastRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDatasetMetadata' : IDL.Func([], [IDL.Opt(DatasetMetadata)], ['query']),
    'getModelSettings' : IDL.Func([], [ModelSettings], ['query']),
    'getSimulationMode' : IDL.Func([], [IDL.Bool], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDatasetMetadata' : IDL.Func([DatasetMetadata], [], []),
    'setSimulationMode' : IDL.Func([IDL.Bool], [], []),
    'updateModelSettings' : IDL.Func([ModelSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };