/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'acknowledged' : boolean,
  'message' : string,
  'timestamp' : string,
  'severity' : string,
}
export interface DatasetMetadata {
  'missingValues' : bigint,
  'filename' : string,
  'timeRange' : string,
  'rowCount' : bigint,
  'uploadedAt' : string,
}
export interface ForecastRecord {
  'predictedLoad' : number,
  'isPeak' : boolean,
  'actualLoad' : number,
  'timestamp' : string,
}
export interface ModelSettings {
  'refreshRate' : bigint,
  'learningRate' : string,
  'xgboostMaxDepth' : bigint,
  'lstmEpochs' : bigint,
  'batchSize' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acknowledgeAlert' : ActorMethod<[bigint], undefined>,
  'addAlert' : ActorMethod<[string, string], bigint>,
  'addForecastRecord' : ActorMethod<[ForecastRecord], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearForecastRecords' : ActorMethod<[], undefined>,
  'getAllAlerts' : ActorMethod<[], Array<Alert>>,
  'getAllForecastRecords' : ActorMethod<[], Array<ForecastRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDatasetMetadata' : ActorMethod<[], [] | [DatasetMetadata]>,
  'getModelSettings' : ActorMethod<[], ModelSettings>,
  'getSimulationMode' : ActorMethod<[], boolean>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDatasetMetadata' : ActorMethod<[DatasetMetadata], undefined>,
  'setSimulationMode' : ActorMethod<[boolean], undefined>,
  'updateModelSettings' : ActorMethod<[ModelSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];